apiVersion: apps/v1
kind: Deployment
metadata:
  name:  auth
  namespace: integration
  labels:
    app:  auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      serviceAccountName: integration-user
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      containers:
      - name: auth
        image: taraskrupko/integrator-auth:1.0.1
        imagePullPolicy: Always
        env:
          - name: DB_SERVER
            valueFrom:
              secretKeyRef:
                name: pgsql-secret
                key: instance
          - name: DB_PORT
            value: "5432" # порт базы данных
          - name: DB_NAME
            value: "integrator_auth" # имя базы данных
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: pgsql-secret
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pgsql-secret
                key: password
          - name: ConnectionStrings__PostgresConnection
            value: "Server=$(DB_SERVER);Port=$(DB_PORT);Database=$(DB_NAME);User Id=$(DB_USER);Password=$(DB_PASSWORD);"
          - name: CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: auth-secret
                key: CLIENT_ID
          - name: CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: auth-secret
                key: CLIENT_SECRET
          - name: CLIENT_NAME
            valueFrom:
              secretKeyRef:
                name: auth-secret
                key: CLIENT_NAME
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 250m
            memory: 250Mi
        livenessProbe:
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
          httpGet:
            path: '/health'
            port: http
        ports:
        - containerPort:  8080
          name: http
      imagePullSecrets:
        - name: regcred
---

apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: integration
  labels:
    app: auth
spec:
  selector:
    app: auth
  type: ClusterIP
  ports:
  - protocol: TCP 
    port: 80
    targetPort: 8080