apiVersion: v1
kind: ServiceAccount
metadata:
  name: integration-user
  namespace: integration
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: integration
  name: integration-user
rules:
- apiGroups: ["apps", ""]
  resources: ["services", "pods", "deployments", "secrets", "configmaps"]
  verbs: ["get", "watch", "list", "update", "create", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: integration-user
subjects:
  - kind: ServiceAccount
    # Reference to ServiceAccount kind's `metadata.name`
    name: integration-user
    # Reference to ServiceAccount kind's `metadata.namespace`
    namespace: integration
roleRef:
  kind: ClusterRole
  name: integration-user
  apiGroup: rbac.authorization.k8s.io